import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {hashPassword} from '../app/auth.mjs';import {createApplication} from '../app/server.mjs';
test('login, role isolation, optional proof, secure download, reset revocation and restart persistence',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'meeting-auth-'));
 const accounts=['admin','alice','bob'].map((username,i)=>({id:'account_'+i,memberId:'member_'+i,username,role:i?'member':'manager',passwordHash:hashPassword('Password-123')}));
 const seed={members:accounts.map(a=>({id:a.memberId,name:a.username})),accounts,todos:[{id:'todo_a',title:'Alice task',ownerId:'member_1',done:false},{id:'todo_b',title:'Bob task',ownerId:'member_2',done:false}],meetings:[{id:"meeting_a",status:"published",title:"已发布",tasks:[],speakers:[]},{id:"meeting_b",status:"review",title:"内部草稿",tasks:[],speakers:[]}]};
 fs.writeFileSync(path.join(dir,'workspace.json'),JSON.stringify(seed));const server=createApplication({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});});
 const base='http://127.0.0.1:'+server.address().port;
 const call=async(route,cookie='',method='GET',body)=>{const r=await fetch(base+route,{method,headers:{Cookie:cookie,'X-Requested-With':'MeetingLocal'},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const login=async(username,password='Password-123')=>call('/api/auth/login','','POST',{username,password});
 assert.equal((await call('/api/todos')).status,401);assert.equal((await login('admin','bad')).status,401);
 const admin=(await login('admin')).cookie,alice=(await login('alice')).cookie,bob=(await login('bob')).cookie;
 assert.equal((await call('/api/todos',alice)).data.todos.length,1);assert.equal((await call('/api/todos',admin)).data.todos.length,2);
 for(const route of ['/api/settings','/api/feishu/config','/api/accounts'])assert.equal((await call(route,alice)).status,403);
 assert.equal((await call('/api/morning-meetings',alice)).data.meetings.length,1);
 assert.equal((await call('/api/morning-meetings/meeting_a',alice)).status,200);
 assert.equal((await call('/api/morning-meetings/meeting_b',alice)).status,404);
 for(const action of ['analyze','publish'])assert.equal((await call('/api/morning-meetings/meeting_a/'+action,alice,'POST',{})).status,403);
 assert.equal((await call('/api/morning-meetings/meeting_a',alice,'DELETE')).status,403);
 assert.equal((await call('/api/members',alice)).data.members.length,1);
 assert.equal((await call('/api/todos/todo_b',alice,'PATCH',{done:true})).status,404);
 assert.equal((await call('/api/todos',alice,'POST',{title:'injection'})).status,403);
 const selfTask=await call('/api/todos',alice,'POST',{title:'自己的新增任务',ownerId:'member_1'});assert.equal(selfTask.status,201);
 assert.equal((await call('/api/todos',alice,'POST',{title:'不能替他人创建',ownerId:'member_2'})).status,403);
 const upload=async()=>{const r=await fetch(base+'/api/morning-meetings/upload?'+new URLSearchParams({fileName:'notes.txt',title:'成员会议',meetingDate:'2026-09-28'}),{method:'POST',headers:{Cookie:alice,'X-Requested-With':'MeetingLocal'},body:'明天交付报告'});assert.equal(r.status,201);return (await r.json()).meeting;};
 const own=await upload();assert.equal(own.uploadedBy,'member_1');
 assert.equal((await call('/api/morning-meetings/'+own.id,bob)).status,404);
 assert.equal((await call('/api/morning-meetings/'+own.id+'/analyze',bob,'POST',{})).status,403);
 assert.equal((await call('/api/morning-meetings/'+own.id,alice)).status,200);
 assert.equal((await call('/api/morning-meetings/'+own.id+'/analyze',alice,'POST',{})).status,200);
 assert.equal((await call('/api/morning-meetings/'+own.id+'/review',alice,'PATCH',{transcript:'明天交付报告',summary:'会议摘要',speakers:[],tasks:[{title:'交付报告',assigneeId:'member_1',sourceExcerpt:'交付报告',dueAt:''}]})).status,200);
 assert.equal((await call('/api/morning-meetings/'+own.id+'/publish',alice,'POST',{})).status,200);
 assert.equal((await call('/api/morning-meetings/'+own.id,bob)).status,200);
 const deletable=await upload();assert.equal((await call('/api/morning-meetings/'+deletable.id,bob,'DELETE')).status,403);assert.equal((await call('/api/morning-meetings/'+deletable.id,alice,'DELETE')).status,200);
 let result=await call('/api/todos/todo_a',alice,'PATCH',{done:true,note:'无附件完成'});assert.equal(result.status,200);assert.equal(result.data.todo.completions[0].attachment,null);
 await call('/api/todos/todo_a',alice,'PATCH',{done:false});
 assert.equal((await call('/api/todos/todo_a',alice,'PATCH',{done:true,attachment:{name:'x.html',base64:'YQ=='}})).status,400);
 result=await call('/api/todos/todo_a',alice,'PATCH',{done:true,note:'附件完成',attachment:{name:'完成证明.txt',base64:Buffer.from('proof').toString('base64')}});assert.equal(result.status,200);
 const proof=result.data.todo.completions.at(-1).attachment;const route='/api/todos/todo_a/attachments/'+proof.id;
 assert.equal((await fetch(base+route,{headers:{Cookie:bob}})).status,404);assert.equal((await fetch(base+route)).status,401);
 const file=await fetch(base+route,{headers:{Cookie:admin}});assert.equal(await file.text(),'proof');assert.match(file.headers.get('content-disposition'),/^attachment;/);
 assert.ok(!(JSON.stringify((await call('/api/accounts',admin)).data)).includes('passwordHash'));
 assert.equal((await call('/api/accounts/member_0',admin,'PUT',{username:'admin',role:'member'})).status,400);
 assert.equal((await call('/api/accounts/member_1',admin,'PUT',{username:'alice',role:'member',password:'New-password-456'})).status,200);
 assert.equal((await call('/api/todos',alice)).status,401);assert.equal((await login('alice')).status,401);
 const fresh=(await login('alice','New-password-456')).cookie;assert.equal((await call('/api/todos',fresh)).status,403);
 assert.equal((await call('/api/auth/password',fresh,'POST',{currentPassword:'New-password-456',password:'Personal-password-789'})).status,200);
 assert.equal((await call('/api/todos',fresh)).status,401);
 const changed=(await login('alice','Personal-password-789')).cookie;assert.equal((await call('/api/todos',changed)).status,200);
 const disk=JSON.parse(fs.readFileSync(path.join(dir,'workspace.json'),'utf8'));assert.equal(disk.todos.find(t=>t.id==='todo_a').completions.length,3);assert.equal(disk.todos.find(t=>t.id==='todo_a').done,true);assert.ok(!JSON.stringify(disk).includes('Personal-password-789'));
});
